# Generated by Django 4.2.7 on 2023-12-28 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=10, unique=True, verbose_name='NIT')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Casa médica',
                'verbose_name_plural': 'Casas médicas',
                'db_table': 'medical_house',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=20, unique=True, verbose_name='Afiliación')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='Número')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('diagnosis', models.CharField(max_length=150, verbose_name='Diagnóstico')),
                ('procedure', models.CharField(max_length=150, verbose_name='Procedimiento quirúrgico')),
                ('service', models.CharField(max_length=20, verbose_name='Servicio o sala')),
                ('bed', models.CharField(max_length=10, verbose_name='No. de cama')),
                ('operation', models.DateField(verbose_name='Fecha de operación')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.medicalhouse', verbose_name='Casa médica')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Pre solicitud',
                'verbose_name_plural': 'Pre solicitudes',
                'db_table': 'pre_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('description', models.CharField(max_length=60, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de estado',
                'verbose_name_plural': 'Tipos de estado',
                'db_table': 'type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uptake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='Número')),
                ('operating_room', models.CharField(max_length=3, verbose_name='No. de quirófano')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('surgeon', models.CharField(max_length=45, verbose_name='Cirujano')),
                ('instrumentalist', models.CharField(max_length=45, verbose_name='Instrumentista')),
                ('circulating', models.CharField(max_length=45, verbose_name='Circulante')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.medicalhouse', verbose_name='Casa médica')),
                ('pre_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.prerequest', verbose_name='Pre solicitud')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.status', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Hoja de consumo',
                'verbose_name_plural': 'Hojas de consumo',
                'db_table': 'uptake',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UptakeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.material', verbose_name='Material')),
                ('uptake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.uptake', verbose_name='Hoja de consumo')),
            ],
            options={
                'verbose_name': 'Detalle de hoja deconsumo',
                'verbose_name_plural': 'Detalles de hoja de consumo',
                'db_table': 'uptake_detail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.type', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PreRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.material', verbose_name='Material')),
                ('pre_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.prerequest', verbose_name='Pre solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de pre solicitud',
                'verbose_name_plural': 'Detalles de pre solicitud',
                'db_table': 'pre_request_detail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='prerequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='prerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.status', verbose_name='Estado'),
        ),
    ]
