# Generated by Django 4.2.7 on 2024-06-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default=None, max_length=200, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='request.status', verbose_name='Estado'),
        ),
    ]
