# Generated by Django 4.2.7 on 2024-06-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_unit_material_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(max_length=450, verbose_name='Descripción'),
        ),
    ]
