# Generated by Django 4.2.7 on 2024-06-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
    ]
