# Generated by Django 4.2.7 on 2024-06-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_material_description_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Descripción'),
        ),
    ]
