# Generated by Django 4.2.7 on 2024-06-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.FloatField(default=0, verbose_name='Existencia'),
        ),
    ]
