# Generated by Django 4.2.7 on 2024-07-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_uptake_user_alter_prerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptake',
            name='status',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='request.status', verbose_name='Estado'),
        ),
    ]
