# Generated by Django 4.2.7 on 2024-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_uptake_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observaciones'),
        ),
    ]
