# Generated by Django 4.2.7 on 2024-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_prerequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='number_siaf',
            field=models.CharField(blank=True, max_length=20, verbose_name='SIAF'),
        ),
    ]
