# Generated by Django 4.2.7 on 2024-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_prerequest_number_siaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequest',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='prerequest',
            name='number_siaf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIAF'),
        ),
    ]
