# Generated by Django 4.2.7 on 2024-07-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_alter_prerequest_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='abort_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Justificación'),
        ),
    ]
