# Generated by Django 4.2.7 on 2024-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_prerequest_abort_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Color'),
        ),
    ]
