# Generated by Django 4.2.7 on 2024-08-02 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_status_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('siaf', models.CharField(max_length=12, verbose_name='SIAF')),
                ('code_igss', models.CharField(max_length=10, verbose_name='Código IGSS')),
                ('ppr', models.CharField(max_length=15, verbose_name='PPR')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.medicalhouse', verbose_name='Casa médica')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'entry',
                'managed': True,
            },
        ),
    ]
