# Generated by Django 4.2.7 on 2024-08-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.CharField(max_length=4, verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Detalle de ingreso',
                'verbose_name_plural': 'Detalles de ingresos',
                'db_table': 'detail_entry',
                'managed': True,
            },
        ),
    ]
