# Generated by Django 4.2.7 on 2024-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_entrydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydetail',
            name='pice_purchase',
            field=models.FloatField(default=0, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Subtotal'),
            preserve_default=False,
        ),
    ]
