# Generated by Django 4.2.7 on 2024-08-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_entrydetail_pice_purchase_entrydetail_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, to='request.status', verbose_name='Estado'),
        ),
    ]
