# Generated by Django 4.2.7 on 2024-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
