# Generated by Django 4.2.7 on 2024-08-02 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydetail',
            name='pice_purchase',
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='price_purchase',
            field=models.FloatField(default=0, verbose_name='Precio compra'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('stock', models.FloatField(default=0, verbose_name='Existencia')),
                ('entry_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.entrydetail', verbose_name='Detalle ingreso')),
                ('status', models.ForeignKey(default=19, on_delete=django.db.models.deletion.PROTECT, to='request.status', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lot',
                'managed': True,
            },
        ),
    ]
