# Generated by Django 4.2.7 on 2024-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_remove_entrydetail_pice_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
