# Generated by Django 4.2.7 on 2024-08-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_entry_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydetail',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='request.entry', verbose_name='Ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
