# Generated by Django 4.2.7 on 2024-08-05 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_entrydetail_entry_alter_entry_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_award',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de adjudicación'),
        ),
        migrations.AddField(
            model_name='entry',
            name='nog',
            field=models.CharField(default=0, max_length=15, verbose_name='NOG'),
            preserve_default=False,
        ),
    ]
