# Generated by Django 4.2.7 on 2024-08-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_entry_date_award_entry_nog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='code_igss',
        ),
    ]
