# Generated by Django 4.2.7 on 2024-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0025_remove_entry_code_igss'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='stock',
            field=models.BooleanField(default=False, verbose_name='De stock'),
        ),
    ]
