# Generated by Django 4.2.7 on 2024-08-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0027_prerequestdetail_lot_alter_prerequestdetail_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequest',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.medicalhouse', verbose_name='Casa médica'),
        ),
        migrations.AlterField(
            model_name='prerequestdetail',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.lot', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='prerequestdetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request.material', verbose_name='Material'),
        ),
    ]
