# Generated by Django 4.2.7 on 2024-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0028_alter_prerequest_house_alter_prerequestdetail_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='decline_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Justificación'),
        ),
    ]
