# Generated by Django 4.2.7 on 2024-08-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0029_prerequest_decline_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequest',
            name='abort_user',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuario quien anula'),
        ),
    ]
