# Generated by Django 4.2.7 on 2024-10-03 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0030_prerequest_abort_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUptake',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=15, verbose_name='Número')),
                ('operating_room', models.CharField(max_length=3, verbose_name='No. de quirófano')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('surgeon', models.CharField(max_length=45, verbose_name='Cirujano')),
                ('instrumentalist', models.CharField(max_length=45, verbose_name='Instrumentista')),
                ('circulating', models.CharField(max_length=45, verbose_name='Circulante')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.medicalhouse', verbose_name='Casa médica')),
                ('pre_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.prerequest', verbose_name='Pre solicitud')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default=9, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.status', verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Hoja de consumo',
                'verbose_name_plural': 'historical Hojas de consumo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPreRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=15, verbose_name='Número')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('diagnosis', models.CharField(max_length=150, verbose_name='Diagnóstico')),
                ('procedure', models.CharField(max_length=150, verbose_name='Procedimiento quirúrgico')),
                ('service', models.CharField(max_length=20, verbose_name='Servicio o sala')),
                ('bed', models.CharField(max_length=10, verbose_name='No. de cama')),
                ('operation', models.DateField(verbose_name='Fecha de operación')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('number_siaf', models.CharField(blank=True, max_length=20, null=True, verbose_name='SIAF')),
                ('abort_comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Justificación')),
                ('abort_user', models.CharField(blank=True, max_length=25, null=True, verbose_name='Usuario quien anula')),
                ('decline_comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Justificación')),
                ('stock', models.BooleanField(default=False, verbose_name='De stock')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.medicalhouse', verbose_name='Casa médica')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.patient', verbose_name='Paciente')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.status', verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Pre solicitud',
                'verbose_name_plural': 'historical Pre solicitudes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('membership', models.CharField(db_index=True, max_length=20, verbose_name='Afiliación')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Paciente',
                'verbose_name_plural': 'historical Pacientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=45, verbose_name='Código')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('stock', models.FloatField(default=0, verbose_name='Existencia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default=6, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.status', verbose_name='Estado')),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'historical Material',
                'verbose_name_plural': 'historical Materiales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('date_award', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de adjudicación')),
                ('nog', models.CharField(max_length=15, verbose_name='NOG')),
                ('siaf', models.CharField(max_length=12, verbose_name='SIAF')),
                ('ppr', models.CharField(max_length=15, verbose_name='PPR')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.medicalhouse', verbose_name='Casa médica')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default=16, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='request.status', verbose_name='Estado')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical Ingreso',
                'verbose_name_plural': 'historical Ingresos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
